### ISSUE TITLE
Probleme with loader

### ISSUE THREAD

**Issue by chenzhenhui** [cbib/XEML-Lab#8]
Hello
We try to find the better strategy to finisk FRIM1 and FRIM2 but we have critical probleme or perhabs just incomprehensible events.
We decides to not use the loader "import from plato file". Not enough flexible and strange result in genotype table.
First. No date of observation point
Second. We obtain a incroyable list of genotypes with almost all the plant (and not only the ten genotype studied)
Third. I said almost because we never arrived to store the exact number of plants of our experiment.
.
So we try the classical method.....
And also....

**Comment by ebouilhol** [comment]
Hello,

Can you be more precise on "critical problems" and "incomprehensible envents" ?

1. First :  "No date of observation point"
- It could happen everywhere in the logiciel, can you tell me where you don't see the date of the observation points ?
- Please name the files you used 

2. Second : "We obtain a incroyable list of genotypes with almost all the plant (and not only the ten genotype studied)"
- When using which file ?

3. Third. I said almost because we never arrived to store the exact number of plants of our experiment.
- Can you give me some screens of the steps you followed ? You can drag and drop images here.

**Comment by chenzhenhui** [comment]
Same comment. Chen will send you a ppt by mail

**Comment by ebouilhol** [comment]
![capture du 2015-02-12 14 35 58](https://cloud.githubusercontent.com/assets/4415638/6263586/02688340-b81a-11e4-8cc7-6bddb1fcfc6f.png)

**Comment by ebouilhol** [comment]
![capture du 2015-02-12 14 35 58](https://cloud.githubusercontent.com/assets/4415638/6263596/1094d342-b81a-11e4-80f6-da469a735cb1.png)

**Comment by chenzhenhui** [comment]
Cher Emmanuel

Je passe au français car ici je m'arrache les cheveux !
Je reprends les problème mentioné ci-dessus. Trop de génotypes produit avec import from plato file!
Nous venons d'essayer avec deux fichiers différents 

FRIM1 12 individus - 1 genotype - 2 traitements :
Lorsque l'on charge la table on obtient dans la fenêtre génotype (6 genotypes identiques)
 et dans le code editor aucun individu.

FRIM2 216 individus - 10 genotype - 2 traitements :
Lorsque l'on charge la table on obtient dans la fenêtre génotype (108 genotypes)
 et dans le code editor 108 individus.

Et Chen m'a montré une fenêtre ahurrissante - sample- avec des mélanges entre génotype CS25, MDH7 and MDH 8 MDH 9 ! Je lui de mande de t'envoyer la copie écran.

Bref, autant te dire qu'il nous est impossible d'avancer dans la définition de la stratégie d'échantillonnage pour aucun FRIM et autant dire que nous sommes loin d'avoir pu tester le pooling. Si tout cela n'est pas clair, je suis joignable au 05 57 12 25 56 cette après-midi maispas demain ni la semaine prochaine.

**Comment by chenzhenhui** [comment]
Il semblerait que le mélange des génotypes est seulement un probleme d'affichage (tabulation mal postionnée ?).
Un nouveau problème qui se pose avec cette nouvelle version 19/02 : quand on veut ajouter les ontologies, la fenêtre se bloque et xeml se ferme.

**Comment by chenzhenhui** [comment]
Et enfin,
Nous voulons travailler avec une plus ancienne version, celle du 5/02 qui ne présentait pas ce problème, mais nous ne pouvons pas car elle a été écrasée par celle d'aujourd'hui. Donc pour cette semaine, nous sommes bloquées.
Si tu peux te concentrer sur la méthode "classique" sans utiliser "import from plato file" et corriger le bug qui ne nous permet pas de renseigner les ontologies et finir de tester "Add samples", on pourra peut-être tester un nouveau FRIM1, juste pour les plantes entières.
Pour être claire, sur les 600 plantes cultivées, nous avons observé 6 plantes en condition "control" et 6 en condition "shading". Nous avons observée des données phénotypiques sur 12 de ces plantes entière (biomasse, hauteur etc...). Il faudrait que l'on puisse générer une table d'experimentation avec les n° ID des plantes (même si ils sont aléatoires pour le moment, nous avions demandé à ce qu'il démarre à 1 et qu'ils soient incrémentés régulièrement pour ne pas avoir à gérer des n° trop longs ingérables en culture car les étiquettes sont trop petites) pour l'intégrer avec notre table de données phénotypiques.
On s'attaquera au pooling après cela ?
Merci Emmanuel.

**Comment by ebouilhol** [comment]
Chère Cécile,

Pas de problèmes pour le français, j'ai bien reçu le mail de Chen et j'essaye de comprendre ce qu'il se passe a partir de cela.

Pour l'affichage des phénotypes je penche pour un affichage différent de ce que vous avez connu jusque la, je l'avait vaguement évoqué avec Chen dans un précédent mail, l'ancienne version affichait un seul génotype avec dedans les individus des autres génotypes, ce qui, me paraissait faire assez peu de sens... (et causait un crash du logiciel lorsque des phénotypes avaient un nombre d'individus différents, le crash que vous nous aviez montré lorsque vous étiez venus)

L'arbre affiche maintenant tous les individuals de tous les génotypes, ce qui, a défaut d'être graphiquement parlant très sympathique, présente l'avantage de pouvoir gérer les individus séparément. Il faudra discuter d'un affichage intuitif pour cette partie, pour qu'elle soit a la fois générique et pratique.

Je vous envoie une nouvelle version avec le problème de fenêtre reglé d'ici quelques minutes... désolé pour ce dernier bug, c'est un effet pervers des quelques modifications que j'ai fait a d'autres endroits...

**Comment by chenzhenhui** [comment]
Hi,
Now when we use "import from plato file" load the csv file directly, it is OK for the genotype.
But when we try to generate a experiment table, there is nothing.

Good luck!

**Comment by ebouilhol** [comment]
Hi,
Can you send me the file you used to generate the experiment table ?

And do you clicked on "Experiment table with all data" or "Experiment table only with environmental data" ?

Thank you !

**Comment by chenzhenhui** [comment]
Good morning,
After load the file, when clicked on  "Experiment table only with environmental data" . Because when we use "Experiment table with all data" , it seems that we have to finish the box and we do not know what it is. Sometimes, the system may also finishes directly with clicking on the botton.


Enclosed is the file we load and even another two questions.
Thank you very much!

CHEN









ÔÚ 2015-03-06 01:07:28£¬"ebouilhol" <notifications@github.com> Ð´µÀ£º


Hi,
Can you send me the file you used to generate the experiment table ?

And do you clicked on "Experiment table with all data" or "Experiment table only with environmental data" ?

Thank you !

¡ª

**Comment by chenzhenhui** [comment]
Hi,
I have sent the files we load to your e_mail.

And when we load the file, we always work with a new XEML which is empty.

Thank you

**Comment by ebouilhol** [comment]
Hi,
I have received your files, thank you !
I'm currently working on ISA-Tab export so I will look at that soon, I will be in touch with you as soon as I find what the problem is !

Thank you,

Emmanul

**Comment by chenzhenhui** [comment]
Hi,

This afternoon we try to load the file of FRIM4, but after we click finish, the system always closed like this.

And this is the csv file.

CHEN








At 2015-03-06 19:23:33, "ebouilhol" <notifications@github.com> wrote:


Hi,
I have received your files, thank you !
I'm currently working on ISA-Tab export so I will look at that soon, I will be in touch with you as soon as I find what the problem is !

Thank you,

Emmanul

¡ª
